### ISSUE TITLE
USER STORY: Register for an account

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp5-gamer-verse#12]
As a user, I can **create a new account**, so that I can **access all the features for signed-up users** including liking and commenting

Acceptance Criteria 1:
Given that I am an unregistered user
When I am on the homepage
Then I can click a button/link which takes me to a registration page

Acceptance Criteria 2:
Given that I am an unregistered user on the user registration page
When I enter my email and password and click on the register button
Then the system creates me an account and signs me in

## Tasks

- [ ] Develop the ability for users to register for an account
- [ ]  Develop a button/link in the navbar to direct users to the registration page
- [ ]  Create a user registration form

**Comment by Jbachtiger** [comment]
Tasks complete.
