### ISSUE TITLE
USER STORY: Create, View, Edit and Delete Posts

### ISSUE THREAD

**Issue by Jbachtiger** [Jbachtiger/ci-pp5-gamer-verse#21]
- As a **user**, I can **create a new post**, so that I can **share my thoughts and opinions** with others

- As a **user**, I can **view all posts**, so that I can **browse all content** on the site

- As a **user**, I can **edit my posts**, so that I can make **changes to existing content**

- As a **user**, I can **delete my posts**, so that I can **remove my content**

Acceptance Criteria 1:
Given that I am a signed-in user
When I navigate to the posts section
Then I have the choice to create a new post

Acceptance Criteria 2:
Given that I am a signed-in user and have created a post
When I save my post
Then it is available for others to read

Acceptance Criteria 3:
Given that I am a user of the website
When I navigate to the posts section
Then I am presented with a list of posts

Acceptance Criteria 4
Given that I am a registered user who has created a post
When I navigate to that post
Then I have the option to edit the details and save changes

Acceptance Criteria 5
Given that I am a registered user who is logged in, and has created a post
When I navigate to the post that I would like to delete
Then I have the option to delete the post

## Tasks

- [x]  Develop a form to enable a user to submit a post
- [x]  Develop a way to save the post
- [x]  Develop validation methods
- [x]  Develop a link for all users to access the posts section
- [x]  Develop an edit button for blog posts of users who are logged in and only applicable to their blogs
- [x]  Develop a delete post button that appears on the post page

**Comment by Jbachtiger** [comment]
Tasks completed.
